using System;

namespace TeamPunk.Enums
{
	public enum PredefParticleMaterial
	{
		PREDEF_MATERIAL_DEFAULT_BLOCK,
		PREDEF_MATERIAL_DEFAULT_CIRCLE,
		PREDEF_MATERIAL_DEFAULT_LIGHT_RAIN,
		PREDEF_MATERIAL_DEFAULT_HEAVY_RAIN,
		PREDEF_MATERIAL_DEFAULT_FEINT_SMOKE,
		PREDEF_MATERIAL_DEFAULT_MEDIUM_SMOKE,
		PREDEF_MATERIAL_DEFAULT_THICK_SMOKE
	}
}
